### ISSUE TITLE
main does not compile on the tokio leg: #1017 calls cold_file_watermark with the pre-#1020 signature (E0308, main.rs:1893)

### ISSUE THREAD

**Issue by TinDang97** [pilotspace/moon#1051]
## Summary

`origin/main` does not compile on the tokio leg (`--no-default-features --features runtime-tokio,jemalloc`) as of `095088ca` (#1017), still true at `52c3936c`. Every PR's tokio check (clippy, nextest, Check macOS/Windows) is red until this is fixed. The default (monoio) build is unaffected because the call is `#[cfg(not(feature = "runtime-monoio"))]`.

## Error (verbatim, `cargo clippy --all-targets --no-default-features --features runtime-tokio,jemalloc`)

```
error[E0308]: mismatched types
    --> src/main.rs:1893:37
     |
1893 |                 cold_file_watermark(disk_offload_base.as_deref(), 0),
     |                 ------------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&[u64]`, found `Option<&Path>`
note: function defined here
    --> src/main.rs:1548:8
1548 |     fn cold_file_watermark(spill_seeds: &[u64], shard_id: u16) -> u64 {
```

## Cause

This is a semantic merge conflict between two PRs that were each green on their own. #1020 (moon#997) changed `cold_file_watermark` to take the proven `spill_seeds` slice. #1017 (moon#914), merged before it, added a new tokio-only call site that uses the old `Option<&Path>` argument. Neither PR's CI saw the other.

## Probable fix (not applied; for the #914/#997 owner to confirm)

`cold_file_watermark(&spill_seeds, 0)`. `spill_seeds` (main.rs:1449) is in scope, and the three other call sites (1820/1851/1865) already pass it. Applied locally as an uncommitted patch, the tokio leg then compiles and clippy-cleans with `-D warnings`.

Found while gating #1013; not included in that PR.

**Comment by TinDang97** [comment]
Fixed by PR #1053, merged as 75375155. The tokio `--shards 1` cold-cut seed now passes the proven `&spill_seeds`, like the three other call sites. Verified with `cargo check --all-targets` on the default and tokio feature sets, tokio clippy, `tests/cold_cut_single_shard_914.rs` 4/4 on a tokio build, and the hosted Check/MSRV/memory legs green on the merge ref. The merge process now type-checks main plus the PR head on both runtimes before every merge, so a clean textual squash can no longer land a broken build.
